### ISSUE TITLE
Is it possible to handle Dirac Live Processor plugin?

### ISSUE THREAD

**Issue by rocchidavide** [kenomaerz/pymcws#6]
Hi and thank you for this package!
Is it possible to handle Dirac Live Processor plugin? I need to switch these buttons programmatically:

![Schermata 2020-06-18 alle 18 56 12](https://user-images.githubusercontent.com/4699633/85049842-85210a80-b195-11ea-9f5f-f2509797694f.png)

**Comment by kenomaerz** [comment]
I don't have much experience with JRiver plugins so far - If their settings are exposed via MCWS, then it could be implemented. However, I didn't see anything in the documentation that would suggest that this is possible.

A workaround might be DSP presets. MCWS has an endpoint to load a DSP preset, and if you could save all your configurations, then it would be possible to load them via pymcws. Is that an option?

**Comment by kenomaerz** [comment]
I threw together a quick implementation of playback_loadDSPPreset in b7104e7. This should work in theory, but a test showed that loading presets doesn't work at all on my box. I posted in the support forum here, it seems to be a current jRiver bug: https://yabb.jriver.com/interact/index.php/topic,125911.0.html

**Comment by kenomaerz** [comment]
JRiver 26.0.95 fixes the bug, and loading presets should work. Let me know if this works for you, example usage at the end of examples.py. The feature is now in the master at 8579ba5 and on pypi (v0.2.2)

**Comment by rocchidavide** [comment]
First of all, thank you for your response.
I updated JRiver to 26.0.95 version, but DSP presets still not working :( Is that the same for you?

**Comment by kenomaerz** [comment]
There was another bug interfering - it works for me unter 26.0.98 now. Maybe test with the standard plugins first, and then check the DIRAC Live one? Otherwise you should post in the JRiver Forums, I think. If you think the problem lies in pymcws, feel free to reopen this ticket :)
