### ISSUE TITLE
Implementing Playback/Playlist

### ISSUE THREAD

**Issue by djprime** [kenomaerz/pymcws#7]
Are there any plans to implement getting the current Playlist? 
http://localhost:52199/MCWS/v1/Playback/Playlist?Zone=-1

I have a use case where I need the current playing track info plus the next few tracks.

If not, I will have a go at implementing it. 
I'm pretty new to Python, but looking through the code it makes some sort of sense to me.

**Comment by kenomaerz** [comment]
I haven't looked at it yet, but a cursory glance tells me it shouldn't be too difficult. Feel free to open a pull request, otherwise I'll try to get it done in the coming days :)

**Comment by djprime** [comment]
Ok, thanks. 
I'll set this aside as a Christmas/New Year project.

**Comment by kenomaerz** [comment]
I implemented this in the 1.1.0 release. It is now on pypi. You can use it like so:

```python
# print the playlist of the default zone
playlist = office.playback.playlist(fields=["Name", "Artist"])
print("Currently playing:")
for item in playlist:
    print("    ", item["Artist"], " - ", item["Name"])
```
Defining fields is optional. Let me know if this works for you. Happy holidays!

**Comment by djprime** [comment]
I've just tried this out, and am having very basic problems.

`import pymcws as mcws`

is giving the following errors:

`Traceback (most recent call last):
  File "C:\Users\David\OneDrive\Desktop\Milonga tools\test Python 3.7.9 stuff\Test.py", line 1, in <module>
    import pymcws as mcws
  File "C:\Users\David\AppData\Roaming\Python\Python37\site-packages\pymcws\__init__.py", line 1, in <module>
    from pymcws.media_server import MediaServer, ApiMediaServer
  File "C:\Users\David\AppData\Roaming\Python\Python37\site-packages\pymcws\media_server.py", line 9, in <module>
    from pymcws.server_mixins import Library, Playback, File, Files, Recipes
  File "C:\Users\David\AppData\Roaming\Python\Python37\site-packages\pymcws\server_mixins.py", line 18, in <module>
    class Files(MediaServerDummy):
  File "C:\Users\David\AppData\Roaming\Python\Python37\site-packages\pymcws\server_mixins.py", line 19, in Files
    from pymcws.api.files import get_image, search, transform_mpl_response
  File "C:\Users\David\AppData\Roaming\Python\Python37\site-packages\pymcws\api\files.py", line 78, in <module>
    zone: Zone = None,
TypeError: 'type' object is not subscriptable`

The problem occurs on pymcws 1.0.1 and 1.1.0, but does not on 1.0.0.

Is this a problem with `Class Zone` in model.py?

I noticed that it wasn't updated between pymcws 1.0.0 and 1.1.0

**Comment by kenomaerz** [comment]
I have upgraded the python version to 3.9 because there are some neat features and 3.7 is the next version that stops to receive development. What you see there is 3.7 reporting the new type hinting syntax as an error. If you upgrade to python 3.9 everything should work - just tested it in an empty project to be sure.

**Comment by djprime** [comment]
OK, I upgraded to Python 3.9.9 and it all works fine for me now.
Thank you.
